### ISSUE TITLE
Authz doesn't work with MsgVote

### ISSUE THREAD

**Issue by whoistiger** [CosmosContracts/juno#190]
### Overview
Specify the type of message through the authz module is `generic --msg-type =/cosmos.gov.v1beta1.msgvote`,Successful authorization, information can be checked.

The same command has been tested in Cosmos and Osmosis.

### query grants
```
ubuntu@server:~$ junod query authz grants juno19gl3j8vvdq54dmh9yg8eu8tpykk7kynjqffx9p juno167rpuac44g9xwesuhfchc2epxr7dzkhpy3n92u
grants:
- authorization:
    '@type': /cosmos.authz.v1beta1.GenericAuthorization
    msg: /cosmos.gov.v1beta1.MsgVote
  expiration: "2023-04-28T10:25:10Z"
pagination:
  next_key: null
  total: "0"
```
### generate tx
```
ubuntu@server:~$ junod tx gov vote 20 yes  --from juno19gl3j8vvdq54dmh9yg8eu8tpykk7kynjqffx9p --generate-only > tx.json
```
### cat tx.json
```
ubuntu@server:~$ cat tx.json
{"body":{"messages":[{"@type":"/cosmos.gov.v1beta1.MsgVote","proposal_id":"20","voter":"juno19gl3j8vvdq54dmh9yg8eu8tpykk7kynjqffx9p","option":"VOTE_OPTION_YES"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}
```
### exec tx.json 
```
ubuntu@server:~$ junod tx authz exec tx.json --from tiger --chain-id juno-1 --gas auto --gas-prices=0.0025ujuno --gas-adjustment=2.0
Enter keyring passphrase:
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account juno167rpuac44g9xwesuhfchc2epxr7dzkhpy3n92u not found: key not found
Usage:
  junod tx authz exec [msg_tx_json_file] --from [grantee] [flags]
```
### keys list
```
ubuntu@iserver:~$ junod keys list
Enter keyring passphrase:
- name: tiger
  type: local
  address: juno167rpuac44g9xwesuhfchc2epxr7dzkhpy3n92u
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A5r2D3Ta7001lyPRgctinI7PfAldvvlE7r2KWha1gsEO"}'
  mnemonic: ""
```
