### ISSUE TITLE
bug: we're building protos wrong :cry: 

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#653]
We've got to move the protos from the sdk back into Juno, because the v0.45.x protos are not on buf.build.  This setup will work for v0.47.x only, as far as I understand it. 

```yaml
version: v1
name: buf.build/CosmosContracts/juno
deps:
  - buf.build/cosmos/cosmos-sdk
  - buf.build/cosmos/cosmos-proto
  - buf.build/cosmos/gogo-proto
  - buf.build/googleapis/googleapis
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
    - COMMENTS
    - FILE_LOWER_SNAKE_CASE
  except:
    - UNARY_RPC
    - COMMENT_FIELD
    - SERVICE_SUFFIX
    - PACKAGE_VERSION_SUFFIX
    - RPC_REQUEST_STANDARD_NAME
```
